TENDERS_INFO_PATH = './tenders/assets/clean_trains_info.csv'
TENDERS_TAG_MAP_PATH = './tenders/assets/tenders_tag.csv'
TENDERS_TOPIC_MAP_PATH = './tenders/assets/tenders_topic.csv'
TENDERS_TAG_PATH = './tenders/assets/tenders_keyword.csv'
TENDERS_TOPIC_PATH = './tenders/assets/matching_result_by_lda.csv'
TENDERS_RELEVANT_PATH = './tenders/assets/clean_relevant_tenders.csv'
TENDERS_CATE_DIV_MAP_PATH = './tenders/assets/cate_div_map.csv'
TENDERS_RELATION_MAP_PATH = './tenders/assets/tenders_relation_map.csv'
TENDERS_EMAIL_PATH = './tenders/assets/tenders_email.csv'

LOCAL_PATH = './assets'
MODEL_FILE = '../tenders/assets/LdaModel.model'

RESEARCHER_INFO_PATH = './researcher/assets/researcher_info.csv'
REG_RESEARCHER_INFO_PATH = './researcher/assets/reg_researcher_info.csv'
RESEARCHER_TAG_MAP_PATH = './researcher/assets/researcher_tag.csv'
RESEARCHER_DIVISION_MAP_PATH = './researcher/assets/researcher_division.csv'
RESEARCHER_TAG_DIV_MAP_PATH = './researcher/assets/tag_division_map.csv'
RESEARCHER_ACTION_PATH = './researcher/assets/researcher_action.csv'

